'use strict';
var OFF = 0;
var ERR = 2;

module.exports = {
    extends: [
        'spt',
    ],

    rules: {
        'array-bracket-spacing': ERR,
        'array-callback-return': ERR,
        'arrow-body-style': [ERR, 'as-needed'],
        'arrow-spacing': ERR,
        'block-spacing': ERR,
        'brace-style': [ERR, '1tbs', { allowSingleLine: true }],
        'comma-dangle': [ERR, 'always-multiline'],
        'computed-property-spacing': ERR,
        'eqeqeq': [ERR, 'smart'],
        'max-depth': [ERR],
        'max-len': [ERR, { code: 140, ignoreTrailingComments: true, ignoreUrls: true }],
        'max-params': [ERR, 5],
        'newline-per-chained-call': ERR,
        'no-case-declarations': ERR,
        'no-class-assign': ERR,
        'no-cond-assign': [ERR, 'always'],
        'no-confusing-arrow': [ERR, { allowParens: true }],
        'no-console': ERR,
        'no-debugger': ERR,
        'no-duplicate-imports': ERR,
        'no-else-return': OFF,
        'no-eq-null': OFF,
        'no-negated-condition': ERR,
        'no-negated-in-lhs': ERR,
        'no-shadow': [ERR, { builtinGlobals: true, allow: ['resolve', 'reject', 'cb', 'err'] }],
        'no-shadow-restricted-names': ERR,
        'no-spaced-func': ERR,
        'no-trailing-spaces': ERR,
        'no-undefined': OFF,
        'no-use-before-define': [ERR, { functions: false }],
        'no-useless-call': ERR,
        'no-useless-escape': ERR,
        'one-var': [ERR, 'never'],
        'prefer-spread': ERR,
        'prefer-template': ERR,
        'quote-props': [ERR, 'consistent-as-needed'],
        'quotes': [ERR, 'single', { avoidEscape: true }],
        'space-before-function-paren': ERR,
        'space-infix-ops': ERR,
        'space-unary-ops': ERR,
        'template-curly-spacing': ERR,
        'vars-on-top': OFF,
        'yoda': ERR,
    },
};
